services:
  - type: web
    name: offline-notes-app
    env: node
    buildCommand: npm install && cd client && npm install && cd .. && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: ./server.db
